export const locations = [
  { location: 'A동 301호 앞(과방)', partition: { type: 'column', number: 3 } },
  { location: 'A동 3층 계단 앞', partition: { type: 'column', number: 3 } },
  { location: 'A동 2층 217호 앞(서점쪽 계단)', partition: { type: 'column', number: 3 } },
  { location: 'B동 3층 중앙계단', partition: { type: 'column', number: 3 } },
  { location: 'B동 안뜰로 가는 통로', partition: { type: 'row', number: 3 } },
  { location: 'A,C동 넘어가는 계단 앞', partition: { type: 'row', number: 3 } },
  { location: 'C동 3층 경사로(352-2호 앞)', partition: { type: 'row', number: 3 } },
  { location: 'C동 끝 3~4층 계단', partition: { type: 'row', number: 3 } },
  { location: '새천년관 3층', partition: { type: 'row', number: 3 } },
  { location: '새천년관 4층A', partition: { type: 'row', number: 3 } },
  { location: '새천년관 4층B', partition: { type: 'row', number: 3 } },
  { location: '새천년관 4층C', partition: { type: 'row', number: 3 } },
  { location: '새천년관 4층D', partition: { type: 'row', number: 3 } },
  { location: '새천년관 4층E', partition: { type: 'row', number: 3 } },
  { location: '새천년관 4층F', partition: { type: 'row', number: 3 } },

  { location: '새천년관 5층A', partition: { type: 'row', number: 3 } },
  { location: '새천년관 5층B', partition: { type: 'row', number: 3 } },
  { location: '새천년관 5층C', partition: { type: 'row', number: 3 } },
  { location: '새천년관 5층D', partition: { type: 'row', number: 3 } },
];
